var slotinfo = { 
    timetick : '2019-04-09T10:00:00',
    market : '---',
    type : 'first/others',
    trends_prev : 'descent/ascent/parallel',
    trends_create : 'descent', 
    trends_cur : 'descent',
    config : { },
    status : 'running / liquidation / suspend', 
    liqudation_uid : 'uid-xx-dd-wewerew-dd-00',
    statics : {
        sum_amount : 100,
        sum_amount_done : 90, 
        sum_amount_wait : 10,
        sum_amount_done_ratio : 'amount_done/amount',
        sum_bidkw : 'sum(bidkw)',
        sum_restkw : 'sum(restkw)',
        sum_investkw : 'sum(investkw)',
        average : 'sum_bidkw/sum_amount_done',
        cur_eval_net_ratio : 0.05,
        cur_eval_net_krw : 'cur_eval_net_ratio*sum_bidkw',
    },
    last_bid_info : { timetick : '2019-04-09T10:00:00', tr_price : 6300 },
    add_bid : [
        {
            timetick : '2019-04-09T10:00:00',
            UID : 'uid-xx-dd-wewerew-dd-00',
            status : 'done/wait/wait_expired', 
            p : 0,
            gap : 0,
            amount : 100,
            amount_done : 90, 
            amount_wait : 10,
            amount_done_ratio : 'amount_done/amount',
            bidkw : 'p*amount_done',
            restkw : 'p*amount_wait',
            investkw : 'p*amount',
            deadline : '2019-04-10T10:00:00',
        },
    ],
}

